// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxae62yRMDy7R6uyen1jbyGmonhcJshKk',
    appId: '1:593246564818:web:d17dffb20474c5d460980b',
    messagingSenderId: '593246564818',
    projectId: 'dms-vt',
    authDomain: 'dms-vt.firebaseapp.com',
    storageBucket: 'dms-vt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcmEd15vUYpYV4Qls5cDQZ6F5-vv2a85o',
    appId: '1:593246564818:android:44c1ca81ccdf00c760980b',
    messagingSenderId: '593246564818',
    projectId: 'dms-vt',
    storageBucket: 'dms-vt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBggx5TNniPvL6vRouDkUGER-qVTH5DzAc',
    appId: '1:593246564818:ios:77771d00b258579c60980b',
    messagingSenderId: '593246564818',
    projectId: 'dms-vt',
    storageBucket: 'dms-vt.firebasestorage.app',
    iosBundleId: 'com.colorcraft.colorcraftPaints',
  );
}
